### ISSUE TITLE
Add Sliding text

### ISSUE THREAD

**Issue by shruvar** [PulseZest-Inovation/Royal-Public-School#2]
It should on the top of home page 
![Screenshot 2024-06-08 211303](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/99241665/9f26276e-4a15-4216-a938-30b2e9a6b7c2)

**Comment by im-divxnshh** [comment]
@shruvar please describe in briefly for better understanding

**Comment by im-divxnshh** [comment]
did you mean to fix the all three pictures little bit move up to fix the white empty place?

**Comment by shruvar** [comment]
No i wanted to add a sliding text on the top of home page
![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/99241665/d1ce1296-9671-41c4-9d11-2c3b86feed02)
like this for reference

**Comment by im-divxnshh** [comment]
issue solved branch name ---> issue-solve
