### ISSUE TITLE
Resolve the issue of image slider

### ISSUE THREAD

**Issue by shruvar** [PulseZest-Inovation/Royal-Public-School#3]
Fix the "Next" and "Previous" buttons on the image slider so they don't move when we change the photos.
![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/99241665/90a193d8-9cfe-4c5f-90df-5edd38830698)

**Comment by im-divxnshh** [comment]
fix when image is slide both buttons are not move 
![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/129685502/2e549470-4a23-4872-87f0-0651b92a3731)
![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/129685502/8204724f-ced2-42cc-bf49-4e8fa2df83dc)
