### ISSUE TITLE
Resolve the issue of career UI

### ISSUE THREAD

**Issue by shruvar** [PulseZest-Inovation/Royal-Public-School#4]
1. Move the "Choose File" button so that the entire button is visible.
2. Fix the "Applied Post" field because the full text is not visible, a line appears on the text

![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/99241665/d738a37c-e317-44cc-8de6-e0457be8b8ed)

**Comment by im-divxnshh** [comment]
Application post issue done & plz explain choose file issue briefly 
![image](https://github.com/PulseZest-Inovation/Royal-Public-School/assets/129685502/2381e7d4-2c76-4e51-ba09-b3ef9a73fd6a)
